/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class Tokenizer {
  constructor(bytes: Array<number>)
  encode(input: string, addSpecialTokens: boolean): Array<number>
  decode(ids: Array<number>, skipSpecialTokens: boolean): string
  encodeFast(input: string, addSpecialTokens: boolean): Array<number>
}
